name: Base (Ubuntu:latest)
on:
  push:
    paths:
      - "base/*"
  schedule:
    - cron: 0 0 * * */1
jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: checkout
        uses: actions/checkout@master

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: base/
          tags: |
            bdsmaneger/node_image:latest
            bdsmaneger/node_image:${{ github.run_id }}
          platforms: linux/amd64,linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}